import type { MealDetail } from '../types'

export function printGroceryList(mealDetails: MealDetail[]) {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  })

  const totalMeals = mealDetails.length
  const totalIngredients = mealDetails.reduce((acc, m) => acc + m.ingredients.length, 0)

  const mealsHtml = mealDetails.map(meal => `
    <div class="meal-group">
      <div class="meal-header">
        <img src="${meal.thumb}" alt="${meal.name}" />
        <h3>${meal.name}</h3>
        <span>${meal.ingredients.length} items</span>
      </div>
      <div class="ingredients-grid">
        ${meal.ingredients.map(ing => `
          <div class="ingredient-item">
            <div class="checkbox"></div>
            <div>
              <p class="ing-name">${ing.name}</p>
              <p class="ing-measure">${ing.measure}</p>
            </div>
          </div>
        `).join('')}
      </div>
    </div>
  `).join('')

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Heartly — Grocery List</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;900&family=Plus+Jakarta+Sans:wght@400;600&display=swap');

        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
          font-family: 'Plus Jakarta Sans', sans-serif;
          color: #1f2937;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }

        .print-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          border-bottom: 3px solid #ff6b6b;
          padding-bottom: 20px;
          margin-bottom: 32px;
        }

        .print-logo {
          font-family: 'Nunito', sans-serif;
          font-size: 28px;
          font-weight: 900;
          color: #ff6b6b;
        }

        .print-meta {
          text-align: right;
          font-size: 12px;
          color: #6b7280;
          line-height: 1.6;
        }

        .print-meta strong {
          display: block;
          font-size: 14px;
          color: #374151;
        }

        .meal-group {
          margin-bottom: 28px;
          break-inside: avoid;
        }

        .meal-header {
          display: flex;
          align-items: center;
          gap: 10px;
          margin-bottom: 10px;
          padding: 8px 12px;
          background: #fff8f0;
          border-radius: 12px;
          border-left: 4px solid #ff6b6b;
        }

        .meal-header img {
          width: 36px;
          height: 36px;
          border-radius: 50%;
          object-fit: cover;
        }

        .meal-header h3 {
          font-family: 'Nunito', sans-serif;
          font-weight: 900;
          font-size: 14px;
          flex: 1;
        }

        .meal-header span {
          font-size: 11px;
          color: #9ca3af;
        }

        .ingredients-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 6px;
          padding-left: 8px;
        }

        .ingredient-item {
          display: flex;
          align-items: flex-start;
          gap: 8px;
          padding: 6px 8px;
          border: 1px solid #f3f4f6;
          border-radius: 8px;
        }

        .checkbox {
          width: 14px;
          height: 14px;
          border: 2px solid #ff6b6b;
          border-radius: 4px;
          flex-shrink: 0;
          margin-top: 2px;
        }

        .ing-name {
          font-size: 11px;
          font-weight: 600;
          line-height: 1.3;
        }

        .ing-measure {
          font-size: 10px;
          color: #9ca3af;
        }

        .print-footer {
          margin-top: 40px;
          padding-top: 16px;
          border-top: 1px solid #f3f4f6;
          text-align: center;
          font-size: 11px;
          color: #9ca3af;
        }
      </style>
    </head>
    <body>
      <div class="print-header">
        <div class="print-logo">Heartly.</div>
        <div class="print-meta">
          <strong>Weekly Grocery List</strong>
          ${date}<br>
          ${totalMeals} meals · ${totalIngredients} ingredients
        </div>
      </div>

      ${mealsHtml}

      <div class="print-footer">
        Generated by Heartly — Your weekly meal planner
      </div>
    </body>
    </html>
  `

  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;border:none;'
  document.body.appendChild(iframe)

  const doc = iframe.contentWindow!.document
  doc.open()
  doc.write(html)
  doc.close()

  iframe.contentWindow!.onload = () => {
    iframe.contentWindow!.print()
    setTimeout(() => document.body.removeChild(iframe), 1000)
  }
}